/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "NEAR Documentation",
  "tagline": "NEAR Protocol Developer Documentation",
  "url": "https://docs.near.org",
  "baseUrl": "/zh-CN/",
  "organizationName": "near",
  "projectName": "docs",
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "scripts": [
    "https://buttons.github.io/buttons.js",
    "https://use.fontawesome.com/221fd444f5.js"
  ],
  "stylesheets": [
    "https://fonts.googleapis.com/css2?family=Inter:wght@400;600;900&family=Source+Code+Pro:ital,wght@0,400;0,600;1,400;1,600&display=swap"
  ],
  "favicon": "img/favicon.ico",
  "customFields": {
    "disableHeaderTitle": true,
    "fonts": {
      "myFont": [
        "Inter",
        "sans-serif"
      ]
    },
    "REACT_APP_PUBLIC_POSTHOG_KEY": "phc_95PGQnbyatmj2TBRPWYfhbHfqB6wgZj5QRL8WY9gW20",
    "REACT_APP_PUBLIC_POSTHOG_HOST": "https://eu.i.posthog.com"
  },
  "themes": [
    "@saucelabs/theme-github-codeblock",
    "@docusaurus/theme-mermaid"
  ],
  "onBrokenLinks": "log",
  "onBrokenMarkdownLinks": "log",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "breadcrumbs": true,
          "editUrl": "https://github.com/near/docs/edit/master/website",
          "path": "../docs",
          "sidebarPath": "./sidebars.js",
          "routeBasePath": "/"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5
        },
        "googleAnalytics": {
          "trackingID": "UA-100373569-7",
          "anonymizeIP": true
        },
        "blog": {
          "blogTitle": "NEAR Docs Blog",
          "blogSidebarTitle": "Documentation Blog",
          "blogSidebarCount": "ALL",
          "showReadingTime": true,
          "routeBasePath": "blog",
          "path": "../blog"
        },
        "theme": {
          "customCss": "./src/css/custom.scss"
        }
      }
    ]
  ],
  "plugins": [
    "./src/plugins/monaco-editor",
    "./src/plugins/node-polyfills",
    "docusaurus-plugin-sass",
    [
      "docusaurus-plugin-remote-content",
      {
        "name": "near-changelog",
        "sourceBaseUrl": "https://raw.githubusercontent.com/near/near-releases/main/reports/",
        "outDir": "../blog",
        "documents": [
          "2023-01-31.md",
          "2023-02-28.md",
          "2023-03-31.md",
          "2023-04-30.md",
          "2023-05-31.md",
          "2023-06-30.md",
          "2023-07-31.md",
          "2023-08-31.md",
          "2023-09-30.md",
          "2023-10-31.md",
          "2023-11-30.md",
          "2023-12-31.md",
          "2024-01-31.md",
          "2024-02-29.md"
        ],
        "noRuntimeDownloads": true
      }
    ]
  ],
  "themeConfig": {
    "image": "docs/assets/welcome-pages/protocol.png",
    "announcementBar": {
      "id": "id-0008",
      "content": "🎉 Ethereum Wallets are here! Read more in our <a href=\"/blog/hello-ethereum-wallets\">blogpost</a> and check our <a href=\"/tools/ethereum-wallets\">tutorial to update your app</a> 🎉",
      "backgroundColor": "#fcfbfa",
      "textColor": "#333",
      "isCloseable": true
    },
    "prism": {
      "additionalLanguages": [
        "rust",
        "java",
        "python",
        "ruby",
        "go",
        "typescript",
        "jsx",
        "bash"
      ],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "logo": {
        "alt": "NEAR Logo",
        "src": "img/near_logo.svg",
        "srcDark": "img/near_logo_white.svg"
      },
      "items": [
        {
          "to": "/",
          "label": "Docs",
          "position": "left",
          "activeBaseRegex": "(^/$)|(/build|concepts)"
        },
        {
          "to": "/tutorials/welcome",
          "label": "Tutorials",
          "position": "left",
          "activeBaseRegex": "/tutorials/"
        },
        {
          "type": "dropdown",
          "label": "Tools",
          "position": "left",
          "items": [
            {
              "label": "🧰 All Tools",
              "to": "/tools/welcome"
            },
            {
              "type": "html",
              "value": "<hr/> <small class=\"subtitle\"> Essentials </small>"
            },
            {
              "label": "NEAR API",
              "to": "/tools/near-api-js/quick-reference"
            },
            {
              "label": "NEAR SDK",
              "to": "/tools/sdk"
            },
            {
              "label": "NEAR CLI",
              "to": "/tools/near-cli"
            },
            {
              "type": "html",
              "value": "<hr/> <small class=\"subtitle\"> Wallet Integration </small>"
            },
            {
              "label": "Wallet Selector",
              "to": "/tools/wallet-selector"
            },
            {
              "type": "html",
              "value": "<hr/> <small class=\"subtitle\"> IDEs </small>"
            },
            {
              "label": "VSCode Extension ",
              "href": "https://marketplace.visualstudio.com/items?itemName=near-protocol.near-discovery-ide"
            },
            {
              "label": "BOS Web IDE (Jutsu)",
              "href": "https://jutsu.ai/editor"
            },
            {
              "label": "Remix IDE Plugin",
              "href": "https://docs.welldonestudio.io/code/getting-started"
            }
          ]
        },
        {
          "type": "html",
          "value": "<span class=\"separator\"></span>",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "Resources",
          "position": "left",
          "items": [
            {
              "label": "Github",
              "href": "https://github.com/near",
              "className": "header-github-link"
            },
            {
              "type": "html",
              "value": "<hr/><div class=\"subtitle\"> Support </dib>"
            },
            {
              "href": "https://discord.gg/GZ7735Xjce",
              "label": "Discord"
            },
            {
              "href": "https://t.me/neardev",
              "label": "Telegram"
            },
            {
              "type": "html",
              "value": "<hr /><div class=\"subtitle\"> Education </dib>"
            },
            {
              "href": "https://agorapp.dev/catalog/course?difficulty=&chains=near",
              "label": "Agor"
            },
            {
              "href": "https://learnnear.club/",
              "label": "Learn NEAR Club"
            },
            {
              "type": "html",
              "value": "<hr /><div class=\"subtitle\"> Other Docs </dib>"
            },
            {
              "href": "https://github.com/near/NEPs",
              "label": "NEPs"
            },
            {
              "href": "https://near.github.io/nearcore/",
              "label": "Protocol Docs"
            },
            {
              "href": "https://near-nodes.io",
              "label": "Validator Docs"
            },
            {
              "to": "/integrations/exchange-integration",
              "label": "Exchange Integrations"
            }
          ]
        },
        {
          "to": "/api/rpc/introduction",
          "label": "RPC",
          "activeBaseRegex": "/api/rpc",
          "position": "left"
        },
        {
          "label": "Blog",
          "to": "/blog",
          "activeBaseRegex": "/blog",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "links": [],
      "copyright": "Copyright © 2023 NEAR Protocol",
      "logo": {
        "src": "img/near_logo.svg"
      },
      "style": "light"
    },
    "algolia": {
      "appId": "0LUM67N2P2",
      "apiKey": "50a400220b38e2d4bef996c7d0ed4b90",
      "indexName": "near",
      "contextualSearch": true,
      "searchParameters": {
        "clickAnalytics": true,
        "analytics": true,
        "enableReRanking": true,
        "attributesToRetrieve": [
          "hierarchy.lvl0",
          "hierarchy.lvl1",
          "hierarchy.lvl2",
          "hierarchy.lvl3",
          "hierarchy.lvl4",
          "hierarchy.lvl5",
          "hierarchy.lvl6",
          "type",
          "url",
          "title",
          "description",
          "headers",
          "headersLevels"
        ]
      },
      "placeholder": "Search the Docs...",
      "insights": true,
      "searchPagePath": "search"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "ko",
      "vi",
      "zh-CN"
    ],
    "localeConfigs": {
      "zh-CN": {
        "label": "简体中文",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
