name: 📝 Documentation Request
description: Request new documentation or updates to existing docs
title: "[DOC] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: "## 📝 Documentation Request"

  - type: dropdown
    id: doc_type
    attributes:
      label: "Documentation Type"
      options:
        - "New Documentation"
        - "Update Existing Documentation"
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: "What needs documentation?"
      placeholder: "Describe what needs to be documented or updated and WHY is it needed."
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: "Acceptance Criteria"
      placeholder: "What exactly needs to be done before this issue can be closed? (e.g., code examples, diagrams, step-by-step guides)"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Resources & References"
      placeholder: "Any relevant resources, existing documentation, code references, or screenshots?"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "🔴 P0 : Missing Critical Documentation"
        - "🟠 P1 : Important Documentation Gap"
        - "🟡 P2 : Documentation Enhancement"
        - "🟢 P3 : Nice to Have"
        - "⚪ P4 : Minor Update"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        | Priority | Name | Description |
        |----------|------|-------------|
        | 🔴 P0 | CRITICAL | Missing documentation blocking team progress |
        | 🟠 P1 | HIGH | Important documentation gap affecting productivity |
        | 🟡 P2 | MEDIUM | Significant documentation enhancement |
        | 🟢 P3 | NORMAL | Helpful documentation addition |
        | ⚪ P4 | LOW | Minor documentation update |