name: Upload to Crowdin on PR merge

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - master
  workflow_dispatch:

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build & upload Crowdin docs
        run: |
          echo PR #${{ github.event.number }} has been merged
          cd website && yarn
          yarn build
          yarn crowdin:build
          yarn crowdin:sync
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192