name: Close Stale Issues & Pull Requests

on:
  schedule:
    - cron: '0 0 * * 5'  # Run at midnight on Fridays

permissions:
  issues: write
  pull-requests: write

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale pull requests
        uses: actions/stale@v9.0.0

        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 180
          days-before-pr-stale: 45
          days-before-close: 0
          close-issue-message: 'This issue has been automatically closed because it has been 
inactive for more than 180 days. Please reopen and prioritize this for development if it is 
essential.'
          close-pr-message: 'This pull request has been automatically closed because it has been 
inactive for more than 45 days. Please reopen and see this PR through its review if it is 
essential.'
